# Generated by Django 5.2.1 on 2025-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_contact_number', models.CharField(max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
