# Generated by Django 5.2.1 on 2025-05-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
